### PR TITLE
SETI-5730: Fix sonar vulnerabilities and bugs

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR104

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/3/ : SUCCESS in 1m 14s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/130/ : FAILURE in 29m 53s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/41/ : SUCCESS in 10s

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 1 BUG

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR104

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/4/ : FAILURE in 1m 38s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR104

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/5/ : SUCCESS in 1m 23s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR104

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/6/ : SUCCESS in 1m 09s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR104

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/7/ : SUCCESS in 1m 17s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/135/ : FAILURE in 26m 13s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/46/ : SUCCESS in 7s

**Comment by petr-klemsinsky** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/136/ : FAILURE in 24m 14s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/47/ : SUCCESS in 8s

**Pull request merged**
