### PR TITLE
SETI-5730: Fix sonar vulnerabilities and bugs

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR103

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/1/ : SUCCESS in 1m 30s

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=zuul-check-extended-sonar-PR103

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-sonarqube-scan-zuul-extended/2/ : SUCCESS in 1m 17s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/129/ : FAILURE in 44m 30s
- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/35/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/zuul-fossa-scanning-zuul-el7/2/ : SUCCESS in 1m 14s (non-voting)

**Pull request merged**
