### PR TITLE
SETI-883: Run tox test on py27 instead of py26

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/37/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul/43/ : FAILURE in 30s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/42/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/48/ : FAILURE in 7m 08s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/45/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/51/ : SUCCESS in 6m 24s

**Pull request merged**
