### PR TITLE
SETI-1322: remove the github status link on pipeline end

### PR DESCRIPTION
**Pull request by hrubi**

### CODE REVIEW

**Comment by janpriessnitz** [comment]
Looks ok to me. Someone pls merge.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/105/ : SUCCESS in 10s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/123/ : SUCCESS in 7m 50s

**Comment by hrubi** [comment]
I've also tested setting the commit status with github3.py and checked that the link has disappeared on the last call:
```
import github3
gh = github3.login(token='cc123fb78fc3b874d1ed8500daea6114e0f105d9')
repo = gh.repository('hrubi', 'ci-infra')
repo.create_status('753ddfa086ada48798f52546a3cdfb84bd7f01c5', 'pending', 'http://example.com', '', 'gate')
repo.create_status('753ddfa086ada48798f52546a3cdfb84bd7f01c5', 'pending', '', '', 'gate')
```

**Comment by hrubi** [comment]
I've also tested setting the commit status with github3.py and checked that the link has disappeared on the last call:
```
import github3
gh = github3.login(token='cc123fb78fc3b874d1ed8500daea6114e0f105d9')
repo = gh.repository('hrubi', 'ci-infra')
repo.create_status('753ddfa086ada48798f52546a3cdfb84bd7f01c5', 'pending', 'http://example.com', '', 'gate')
repo.create_status('753ddfa086ada48798f52546a3cdfb84bd7f01c5', 'pending', '', '', 'gate')
```

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/17/ : SUCCESS in 12s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/125/ : SUCCESS in 12m 18s

**Pull request merged**
