### PR TITLE
DO NOT MERGE: Test if raising waitUntilSettled timeout fixes the tests

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/10/ : SUCCESS in 13s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/176/ : FAILURE in 8m 02s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/11/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/177/ : FAILURE in 9m 20s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/12/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/178/ : FAILURE in 7m 07s

**Comment by janpriessnitz** [comment]
ok to test

**Pull request closed without merging**
