### PR TITLE
SETI-2250: Decouple existing "pause" ability from regular exit

### PR DESCRIPTION
**Pull request by janpriessnitz**
Provide a possibility to invoke zuul's pause function
independently. This will allow users to send a signal (SIGUSR2) to
stop zuul from processing any new events. Zuul will continue to
manage any existing jobs and will report them accordingly.

After sending zuul an exit signal, zuul will save the unprocessed
events to a file. After startup, zuul will recover these events
from the file and process them.

This enables users to restart zuul server without losing any
events:
1) Send SIGUSR2 to pause zuul
2) Wait for existing jobs to finish
3) Restart zuul

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/51/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/18/ : FAILURE in 22m 48s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/52/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/19/ : FAILURE in 19m 31s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/55/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/23/ : ABORTED in 21m 46s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/56/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/24/ : ABORTED in 3m 33s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/57/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/25/ : SUCCESS in 7m 08s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/15/ : SUCCESS in 31s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/26/ : SUCCESS in 7m 12s

**Pull request merged**
