### PR TITLE
SETI-2840: Support for dependency on multiple jobs

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/60/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/29/ : FAILURE in 16m 21s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/61/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/30/ : FAILURE in 13m 42s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/64/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/34/ : ABORTED in 4m 13s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/65/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/36/ : ABORTED in 1h 00m 02s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/67/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/38/ : ABORTED in 19m 26s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/68/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 0s
- zuul-docker-tox-zuul : SKIPPED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/69/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 0s
- zuul-docker-tox-zuul : SKIPPED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/70/ : Tests on opensource repositories should be triggered by users in `gooddata` organization in 0s
- zuul-docker-tox-zuul : SKIPPED

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/71/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/39/ : SUCCESS in 23m 47s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/18/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/40/ : ABORTED in 25m 11s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/19/ : SUCCESS in 1m 49s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/41/ : SUCCESS in 25m 36s

**Pull request merged**
