### PR TITLE
SETI-2095: Remove Gerrit integration test

### PR DESCRIPTION
**Pull request by hrubi**
We have decided to drop the Zuul -> Gerrit configuration as there are
only few projects on Gerrit which run some tests via zuul. They
were/will be migrated to GitHub. Therefore there's no need to test the
integration between the two systems, which only adds maintenance
overhead (key rotations, occasional hiccups).

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/35/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/4/ : FAILURE in 8m 25s

**Comment by hrubi** [comment]
Fixing the tests in https://github.com/gooddata/zuul/pull/72

**Comment by michalvanco** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/37/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/7/ : SUCCESS in 8m 03s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/11/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/8/ : SUCCESS in 7m 29s

**Pull request merged**
