### PR TITLE
SETI-6071: Lock jwcrypto version in pip

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/137/ : FAILURE in 32s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/48/ : SUCCESS in 10s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by bkompis** [comment]
Merging manually

**Pull request merged**
