### PR TITLE
INFRA-1406 Build zuul with python3 for el9

### PR DESCRIPTION
**Pull request by vonsch**
we need zuul-cloner on el9 jenkins slaves

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by vonsch** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/165/ : FAILURE in 6m 03s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/72/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/166/ : FAILURE in 22m 02s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/41/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/zuul-fossa-scanning-zuul/1/ : SUCCESS in 1m 07s (non-voting)

**Pull request merged**
