### PR TITLE
SETI-1667: Log skipped jobs due to job filters

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/5/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/171/ : FAILURE in 9m 26s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/6/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/172/ : FAILURE in 8m 30s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/17/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/184/ : SUCCESS in 17m 16s

**Comment by hrubi** [comment]
I've pushed a rebase to pick up the gear version lock.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/21/ : SUCCESS in 9s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/192/ : FAILURE in 21m 02s

**Comment by hrubi** [comment]
I've put `OS_LOG_LEVEL:-DEBUG` into .testr.conf and ran: ` tox -e py27 'tests.test_github.TestGithub.test_pull_unmatched_file_event'`. But I don't see the log message in .testrepository/X.
I've also tried to raise exception in the `if` block https://github.com/gooddata/zuul/pull/65/files#diff-eb5ea697320f538e785ddf2c1fe3dcebR160 and the test didn't hit the exception.

Any clues?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/23/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/194/ : ABORTED in 7m 23s

**Comment by janpriessnitz** [comment]
@hrubi I tried the same thing with the exception and it raised an exception as expected (https://ci.intgdc.com/job/zuul-tox-zuul-el7/194/console).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/25/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/196/ : SUCCESS in 6m 58s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/27/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/198/ : SUCCESS in 6m 53s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/9/ : SUCCESS in 13s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/205/ : SUCCESS in 10m 01s

**Pull request merged**
