### PR TITLE
SETI-7066: Lock version of voluptuous

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/143/ : FAILURE in 34m 40s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/53/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/152/ : FAILURE in 2m 28s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/59/ : SUCCESS in 15s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/154/ : FAILURE in 2m 05s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/61/ : SUCCESS in 16s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by r0039** [comment]
LGTM

**Pull request merged**
