### PR TITLE
SETI-2196: Specify RPM deps to support {name}-docker-tox-zuul job

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/42/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/13/ : SUCCESS in 10m 01s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/4/ : SUCCESS in 11m 37s (non-voting)

**Comment by jakub-plichta** [comment]
LGTM

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-opensource-repository-check/44/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/15/ : SUCCESS in 8m 38s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/6/ : SUCCESS in 10m 23s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/12/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/zuul/job/zuul-tox-zuul/16/ : SUCCESS in 11m 03s
- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/7/ : FAILURE in 18m 40s (non-voting)

**Pull request merged**
