### PR TITLE
SETI-866: Raise timeouts for integration tests

### PR DESCRIPTION
**Pull request by hrubi**
Raise the timeout for the gate to be the same as for the check, which is
5 minutes.

30 seconds was really too few.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/39/ : SUCCESS in 16s
- https://ci.intgdc.com/job/zuul-tox-zuul/45/ : FAILURE in 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/40/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul/46/ : FAILURE in 5s

**Comment by hrubi** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/43/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/49/ : FAILURE in 48s

**Comment by hrubi** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/46/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/52/ : SUCCESS in 8m 46s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/5/ : SUCCESS in 12s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/53/ : FAILURE in 9m 39s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/47/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/54/ : FAILURE in 10m 01s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/6/ : SUCCESS in 22s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/55/ : FAILURE in 10m 06s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/48/ : SUCCESS in 9s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/56/ : SUCCESS in 8m 10s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/7/ : SUCCESS in 10s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/57/ : SUCCESS in 6m 31s

**Pull request merged**
