### PR TITLE
SETI-5687: Sleep 2s after hook is deliver and before zuul fetch PR

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/112/ : FAILURE in 5m 50s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/29/ : SUCCESS in 11s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/117/ : ABORTED in 5m 25s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/30/ : SUCCESS in 10s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/118/ : FAILURE in 5m 19s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/31/ : SUCCESS in 6s

**Comment by bkompis** [comment]
LGTM

**Comment by bkompis** [comment]
Going to merge directly because the tests would prevent merging via the regular pipeline. Following steps to deliver the change (build + change puppet versionlock) will be done by Hung.

**Pull request merged**
