### PR TITLE
SETI-1323: Reduce API calls to GitHub

### PR DESCRIPTION
**Pull request by hrubi**

### CODE REVIEW

**Comment by hrubi** [comment]
@janpriessnitz please check this sketch out.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/101/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/119/ : SUCCESS in 7m 20s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/109/ : SUCCESS in 8s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/129/ : SUCCESS in 8m 55s

**Comment by janpriessnitz** [comment]
ok to merge

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/110/ : SUCCESS in 17s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/130/ : FAILURE in 17m 59s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/19/ : SUCCESS in 23s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/131/ : FAILURE in 17m 47s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/20/ : SUCCESS in 17s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/132/ : SUCCESS in 7m 34s

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/21/ : SUCCESS in 13s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/133/ : ABORTED in 1m 49s

**Comment by hrubi** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/111/ : SUCCESS in 10s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/134/ : ABORTED in 1m 18s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/22/ : SUCCESS in 13s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/135/ : SUCCESS in 7m 20s

**Pull request merged**
