### PR TITLE
SETI-381: Fix typo: add_label -> add_labels

### PR DESCRIPTION
**Pull request by janpriessnitz**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/31/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul/37/ : FAILURE in 1m 03s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/33/ : SUCCESS in 6s
- https://ci.intgdc.com/job/zuul-tox-zuul/39/ : FAILURE in 1m 27s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/41/ : SUCCESS in 7s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/47/ : FAILURE in 49s

**Comment by janpriessnitz** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/49/ : SUCCESS in 9s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/58/ : SUCCESS in 7m 16s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/8/ : SUCCESS in 10s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/59/ : SUCCESS in 9m 05s

**Pull request merged**
