### PR TITLE
SETI-6575: Adapt zuul spec file for el8 and python3

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/141/ : FAILURE in 27m 28s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/51/ : SUCCESS in 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/142/ : FAILURE in 34m 15s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/52/ : SUCCESS in 11s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by daovietduy99** [comment]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/146/ : FAILURE in 32m 57s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/zuul-merge-compliance-check/38/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/compliance/job/zuul-fossa-scanning-zuul-el7/4/ : SUCCESS in 1m 10s (non-voting)

**Pull request merged**
