### PR TITLE
SETI-5534: Lock Github3.py version to 1.3.0

### PR DESCRIPTION
**Pull request by caohhung**
As newer version require higher python version and may
break other integration

Proper solution will be done in SETI-3827

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/106/ : FAILURE in 25m 39s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/24/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/zuul/job/zuul-docker-tox-zuul/111/ : FAILURE in 26m 16s
- https://checklist.intgdc.com/job/compliance/job/zuul-oss-check/28/ : SUCCESS in 11s

**Comment by chiendm** [comment]
LGTM

**Pull request merged**
