### PR TITLE
SETI-1023: extract filenames after push event correctly

### PR DESCRIPTION
**Pull request by hrubi**
It works like this:
```
> gh = github3.login('mytoken')
> repo = gh.repository('gooddata', 'ci-infra')
> [f['filename'] for f in repo.compare_commits('c403edb', '4d73941').files]
[u'.jenkins-jobs.ini.tpl', u'jenkins/jobs/templates/util-jobs.yaml']
```

### CODE REVIEW

**Comment by hrubi** [comment]
Obviously we're missing integration tests - TBD as a part of this PR. It's a bit tricky, because we have to check directly in jenkins that the post-merge job was triggered.
@janpriessnitz do you have some better idea?

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/zuul-opensource-repository-check/100/ : SUCCESS in 10s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/117/ : SUCCESS in 8m 02s

**Comment by janpriessnitz** [comment]
ok to merge

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/zuul-merge-compliance-check/16/ : SUCCESS in 17s
- https://ci.intgdc.com/job/zuul-tox-zuul-el7/118/ : SUCCESS in 8m 06s

**Pull request merged**
